<a href="https://colab.research.google.com/github/AslauAlexandru/Techwithwarriors-Generative-AI-Internship-Tasks/blob/main/TECHWITHWARRIORS_Generative_AI_Internship_Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 01

Generate simple text using a pre-trained GPT model.

Task Details: Use a pre-trained GPT model to generate
coherent and contextually relevant text.

In [1]:
!pip install transformers
!pip install accelerate

# Generate simple text using GPT model: GPT-2 model

In [2]:
import torch
from transformers import AutoTokenizer,LlamaTokenizer, LlamaForCausalLM, AutoModelForCausalLM
# Model name
model_name = "gpt2"
# Tokenize the text
tokenizer = AutoTokenizer.from_pretrained(model_name)
# Create a model for causal language modeling
model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, attn_implementation="sdpa")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [3]:
# Define the prompt
prompt = "Hello, how are you today?"

In [4]:
# Tokenize the prompt
input_ids = tokenizer.encode(prompt, return_tensors="pt")

print(type(input_ids))
print(torch.Tensor)
print(input_ids)

<class 'torch.Tensor'>
<class 'torch.Tensor'>
tensor([[15496,    11,   703,   389,   345,  1909,    30]])


In [5]:
# Generate text
output = model.generate(input_ids=input_ids)

print(output)
type(output)
print(torch.Tensor)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1249: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([[15496,    11,   703,   389,   345,  1909,    30,   198,   198,    40,
          1101,   523,  3772,   284,   307,   994,    13,   314,  1101,   523]])
<class 'torch.Tensor'>


In [6]:
# Decode and print the generated text
generated_text = tokenizer.decode(output[0])

In [7]:
print(generated_text)

Hello, how are you today?

I'm so happy to be here. I'm so


In [8]:
# Generate text
output = model.generate(input_ids=input_ids ,
                        max_length=100,
                        num_return_sequences=1)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [9]:
print(output)

tensor([[15496,    11,   703,   389,   345,  1909,    30,   198,   198,    40,
          1101,   523,  3772,   284,   307,   994,    13,   314,  1101,   523,
          3772,   284,   307,   994,    13,   314,  1101,   523,  3772,   284,
           307,   994,    13,   314,  1101,   523,  3772,   284,   307,   994,
            13,   314,  1101,   523,  3772,   284,   307,   994,    13,   314,
          1101,   523,  3772,   284,   307,   994,    13,   314,  1101,   523,
          3772,   284,   307,   994,    13,   314,  1101,   523,  3772,   284,
           307,   994,    13,   314,  1101,   523,  3772,   284,   307,   994,
            13,   314,  1101,   523,  3772,   284,   307,   994,    13,   314,
          1101,   523,  3772,   284,   307,   994,    13,   314,  1101,   523]])


In [10]:
# Decode and print the generated text
generated_text = tokenizer.decode(output[0],
                                  skip_special_tokens=True)

In [11]:
print(generated_text)

Hello, how are you today?

I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so happy to be here. I'm so


In [12]:
# Generate text
output = model.generate(input_ids=input_ids ,
                        max_length=100,
                        num_return_sequences=1,
                        temperature=1.0,
                        repetition_penalty=2.0,
                        top_p=0.9)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:545: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [13]:
# Decode and print the generated text
generated_text = tokenizer.decode(output[0],
                                  skip_special_tokens=True)

In [14]:
print(generated_text)

Hello, how are you today?
I'm so happy to be here. I've been working on this project for a while now and it's finally finished! It was really fun doing the first part of my story but then when we started writing our second chapter in January 2015 (and that is before Christmas), things got outta hand because there were too many people who didn't like what they saw as being wrong about me or not liking something at all… So after reading your blog post yesterday


# Q&A

In [15]:
from transformers import pipeline

# create pieline for QA
qa = pipeline('question-answering', model='gpt2')

Some weights of GPT2ForQuestionAnswering were not initialized from the model checkpoint at gpt2 and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [16]:
context = '''George Washington (February 22, 1732 – December 14, 1799) was an American Founding Father,
military officer, and politician who served as the first president of the United States from 1789 to 1797.
Appointed by the Second Continental Congress as commander of the Continental Army in 1775,
Washington led Patriot forces to victory in the American Revolutionary War and then served as president
of the Constitutional Convention in 1787, which drafted the current Constitution of the United States.
Washington has thus become commonly known as the "Father of his Country".
Washington's first public office, from 1749 to 1750, was as surveyor of Culpeper County in the Colony of Virginia.
In 1752, he received military training and was granted the rank of major in the Virginia Regiment.
During the French and Indian War, Washington was promoted to lieutenant colonel in 1754 and subsequently became head of
the Virginia Regiment in 1755. He was later elected to the Virginia House of Burgesses and was named a delegate to
the Continental Congress in Philadelphia, which appointed him commander-in-chief of the Continental Army.
Washington led American forces to a decisive victory over the British in the Revolutionary War,
leading the British to sign the Treaty of Paris, which acknowledged the sovereignty and independence of the United States.
He resigned his commission in 1783 after the conclusion of the Revolutionary War.
Washington played an indispensable role in adopting and ratifying the Constitution,
which replaced the Articles of Confederation in 1789.
He was then twice elected president unanimously by the Electoral College in 1788 and 1792.
As the first U.S. president, Washington implemented a strong,
well-financed national government while remaining impartial in a fierce rivalry that emerged between cabinet members
Thomas Jefferson and Alexander Hamilton. During the French Revolution,
he proclaimed a policy of neutrality while additionally sanctioning the Jay Treaty.
He set enduring precedents for the office of president, including republicanism, a peaceful transfer of power,
the use of the title "Mr. President", and the two-term tradition.
His 1796 farewell address became a preeminent statement on republicanism in which he wrote about
the importance of national unity and the dangers that regionalism, partisanship, and foreign influence pose to it.
Washington's image is an icon of American culture. He has been memorialized by monuments,
a federal holiday, various media depictions, geographical locations including the national capital,
the State of Washington, stamps, and currency. In 1976, Washington was posthumously promoted to the rank of general of the Armies,
the highest rank in the U.S. Army.
Washington consistently ranks in both popular and scholarly polls as one of the greatest presidents in American history.'''

In [17]:
question = "Explain me in some words who was George Washington?"
print('Question:',question)
print('Answer:',qa(context = context, question = question)['answer'])

Question: Explain me in some words who was George Washington?
Answer:  independence


# Other text generation using GPT

In [18]:
from accelerate import Accelerator
accelerator = Accelerator()

In [19]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

In [20]:
#device = "cuda" # the device to load the model onto
device = accelerator.device

In [21]:
model = AutoModelForCausalLM.from_pretrained("gpt2", torch_dtype=torch.float16, attn_implementation="sdpa")
tokenizer = AutoTokenizer.from_pretrained("gpt2")

In [22]:
prompt = "Tell me about George Washington."

In [23]:
model_inputs = tokenizer([prompt], return_tensors="pt").to(device)
model.to(device)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [24]:
generated_ids = model.generate(**model_inputs, max_new_tokens=500, do_sample=True)
tokenizer.batch_decode(generated_ids)[0]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"Tell me about George Washington.\n\nYou might have heard of him. You might have heard about him in his speeches. You might have heard of him in his speeches and all that kind of stuff about him. I do know how to say this.\n\nAnd why should I call anyone a name? You may know somebody like a George Washington. You may not know George Washington. We may know somebody who's known George Washington but not at all George Washington.\n\nNo, the thing -- oh, no. Well, George Washington was -- but he's, you know, one of the great presidents of his day and he's -- you know there's a book out recently called George Washington and The End of the Middle East. And, we talked about that book, you know, it comes the day before, I think, the anniversary of the end of the war in Iraq in 2003 -- well, George, you know, I'll do it: I'll come up with a line, I'll come up with a line, this is the line by which we end.\n\nBut in the end, the U.S. is not a superpower. It's not a military superpower. It's not